A coding task has been implemented for the new project, "{{ state.branch.project.name }}", we're working on.

Your job is to analyze the output of the command that was ran and determine if the command was successfully executed.

The current task we are working on is: {{ current_task.description }}

{% if task_steps and step_index is not none -%}
The current task has been split into multiple steps, and each step is one of the following:
* `command` - command to run
* `save_file` -  create or update a file
* `human_intervention` - if the human needs to do something

Here is the list of all steps in in this task (steps that were already completed are marked as COMPLETED, future steps that will be executed once debugging is done are marked as FUTURE, and the current step is marked as CURRENT STEP):
{% for step in task_steps %}
* {% if loop.index0 < step_index %}(COMPLETED){% elif loop.index0 > step_index %}(FUTURE){% else %}(**CURRENT STEP**){% endif %} {{ step.type }}: `{% if step.type == 'command' %}{{ step.command.command }}{% elif step.type == 'save_file' %}{{ step.save_file.path }}{% endif %}`
{% endfor %}

When trying to see if command was ran successfully, take into consideration steps that were previously executed and steps that will be executed after the current step. It can happen that command seems like it failed but it will be fixed with next steps. In that case you should consider that command to be successfully executed.
{%- endif %}

I ran the command `{{ cmd }}`, and it {% if status_code is none %}timed out{% else %}exited with status code {{ status_code }}{% endif %}.
{% if stdout %}
Command stdout:
```
{{ stdout }}
```
{% endif %}
{% if stderr %}
Command stderr:
```
{{ stderr }}
```
{% endif %}

Think about the output and result of this command in the context of current task and current step. Provide detailed analysis of the output and determine if the command was successfully executed.
Output your response in the following JSON format:
```
{
    "analysis": "Detailed analysis of the command results. In this error the command was successfully executed because...",
    "success": true
}
```
